### PR TITLE
Patched DataFusion, Oct 7, 2024

### PR DESCRIPTION
**Pull request by alamb**
- Part of https://github.com/influxdata/influxdb_iox/issues/12626
- Follow on to https://github.com/influxdata/arrow-datafusion/pull/42

This PR is not intended to merge.

This PR documents the contents of the https://github.com/influxdata/arrow-datafusion/commits/df-upgrade-oct-7/ branch

Based on DataFusion at the end of day Oct 7 2024: 577e4bba0f5838846862621e1f5318c949cff2cb

Here are all the changes that went in upstream since https://github.com/influxdata/arrow-datafusion/pull/42
- https://github.com/influxdata/arrow-datafusion/compare/02427674eef658b9b0acb7142f18e8c1520bdb17...influxdata:arrow-datafusion:577e4bba0f5838846862621e1f5318c949cff2cb

Patch list:
* You can see the changes by looking at the commits on this PR

### CODE REVIEW

**Comment by wiedld** [comment]
@alamb -- let me know if I should review this one.


Note that we'll also need to add in[ this upstream DF SHA/patch](https://github.com/apache/datafusion/commit/8d4614d6c43104a13b42c062d957843f25ee32db) to any future DF upgrade.

**Comment by alamb** [comment]
> @alamb -- let me know if I should review this one.

Thanks @wiedld  -- I just want to check a few things first


> 
> Note that we'll also need to add in[ this upstream DF SHA/patch](https://github.com/apache/datafusion/commit/8d4614d6c43104a13b42c062d957843f25ee32db) to any future DF upgrade.

Got it -- can we add a reproducer into iox so we don't forget?

**Comment by alamb** [comment]
Will mark read to review when ready for a look

**Comment by alamb** [comment]
I want to ensure all CI tests pass specifically

**Comment by alamb** [comment]
> @alamb -- let me know if I should review this one.
> 
> Note that we'll also need to add in[ this upstream DF SHA/patch](https://github.com/apache/datafusion/commit/8d4614d6c43104a13b42c062d957843f25ee32db) to any future DF upgrade.

I have added this to this branch

**Comment by wiedld** [comment]
No longer used in iox. Closing.

**Pull request closed without merging**
